ServerName      opinionated-ikiwiki
ServerAdmin     webmaster@localhost
DocumentRoot    /home/ikiwiki/public_html
ErrorLog        /dev/stderr
CustomLog       /dev/stdout combined

<Directory /home/ikiwiki/public_html>
  Options         -Indexes
  AllowOverride   None
  Require         all        granted
</Directory>

<Directory /home/ikiwiki/cgi>
  Options         ExecCGI
  AllowOverride   None
  Require         all       granted
</Directory>

<Directory /usr/lib/git-core>
  Options         ExecCGI
  AllowOverride   None
  Require         all       granted
</Directory>

<Location /auth>
  AuthType       basic
  AuthName       "IkiWiki                        Access"
  AuthUserFile   "/home/ikiwiki/conf/htpasswd"
  Require        valid-user
</Location>

<Location /git>
  SetEnv "GIT_PROJECT_ROOT"                "/home/ikiwiki/conf/git"
  SetEnv "GIT_HTTP_EXPORT_ALL"             ""
  SetEnv "REMOTE_USER"                     "anonymous"
#</Location>

# this works, so long as path is exactly /git/
#<Files "git-http-backend">
    AuthType Basic
    AuthName "Git Access"
    AuthUserFile "/home/ikiwiki/conf/htpasswd"
    Require valid-user
#</Files>
</Location>


ScriptAlias /ikiwiki.cgi      /home/ikiwiki/cgi/ikiwiki.cgi
ScriptAlias /auth/ikiwiki.cgi /home/ikiwiki/cgi/ikiwiki.cgi
ScriptAlias /git              /usr/lib/git-core/git-http-backend
