server.modules += (
    "mod_auth",
    "mod_authn_file",
    "mod_cgi",
    "mod_setenv",
    "mod_accesslog", # accesslog.filename
)

alias.url += (
    "/ikiwiki.cgi" => "/home/ikiwiki/ikiwiki.cgi",
    "/auth/ikiwiki.cgi" => "/home/ikiwiki/ikiwiki.cgi"
)
$HTTP["url"] =~ "/ikiwiki.cgi$" {
    cgi.assign = ( "" => "" )
}
$HTTP["url"] =~ "^/auth" {
    include "/home/ikiwiki/httpauth.conf"
}

$HTTP["url"] =~ "." {
   accesslog.filename = "/dev/stderr"
}
server.breakagelog = "/dev/stderr"
