#!/bin/bash
set -euo pipefail

source $HOME/lib.sh

# is the source directory missing? Re-create it
if [ ! -d /home/ikiwiki/src ]; then
    # XXX we should do this under a lock
    (   # inside a subshell to not leak the environment change
        cd /home/ikiwiki

        # fix "ref updates forbidden inside quarantine environment"
        unset "${!GIT_@}"
        git clone /home/ikiwiki/conf/git/ikiwiki.git src
        restore_dot_ikiwiki
    )
fi

if [ ! -d /home/ikiwiki/public_html ]; then
    # force a full refresh, to pull in underlay files, theme files, etc.
    (
        export PATH=/usr/local/bin:$PATH
        export HOME=/home/ikiwiki
        unset "${!GIT_@}"
        ikiwiki --setup /home/ikiwiki/conf/setup --rebuild --wrappers
    )
else
    exec hooks/post-update.ikiwiki
fi

